spring:
  application:
    name: discovery-server
  cloud:
    config:
      label: docker

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0