spring:
  application:
    name: rest-data-provider-service
  data:
    cache:
      type: redis
    redis:
      host: localhost
      port: 6379

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

simulator:
  update-interval-millis: 5000
  max-updates: 0
  dynamic-spread-alpha: 0.5
  rates:
    - rate-name: PF2_USDTRY
      basePrice: 34.0
      drift: 0.05
      volatility: 0.1
      baseSpread: 0.80
      shockProbability: 0.001
      shockMultiplier: 3.0
      shockDuration: 5
      shockDecayRate: 0.5     # 0.5 => her adımda e^(-0.5*dt) ile shockLevel azalır
      kappa: 0.3             # OU reversion speed
      theta: 35.0            # OU long-term mean
    - rate-name: PF2_EURUSD
      basePrice: 1.05
      drift: 0.02
      volatility: 0.15
      baseSpread: 0.02
      shockProbability: 0.001
      shockMultiplier: 3.0
      shockDuration: 5
      shockDecayRate: 0.3
      kappa: 0.2
      theta: 1.10