services:
  # NGINX
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - microservices-net
    depends_on:
      - api-gateway

  # PROMETHEUS
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - microservices-net

  # GRAFANA
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - microservices-net

  # ELK STACK
  elasticsearch:
    image: elasticsearch:7.17.22
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xms512m"
      - "discovery.type=single-node"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      - microservices-net

  logstash:
    image: logstash:7.17.22
    container_name: logstash
    environment:
      LS_JAVA_OPTS: "-Xmx256m  -Xms256m"
    ports:
      - "5000:5000/tcp"
      - "9600:9600"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9600/_node/pipelines || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 15
      start_period: 30s
    networks:
      - microservices-net
    depends_on:
      elasticsearch:
        condition: service_healthy

  kibana:
    image: kibana:7.17.22
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    ports:
      - "5601:5601"
    networks:
      - microservices-net
    depends_on:
      elasticsearch:
        condition: service_healthy

  # REDIS
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6380"
    command: --port 6380
    volumes:
      - ./redis:/data
    networks:
      - microservices-net
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "6380", "ping" ]
      interval: 1s
      timeout: 2s
      retries: 10

  # RABBITMQ
  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq
    ports:
      - "5673:5672"
    networks:
      - microservices-net
    restart: always

  # ZOOKEEPER AND KAFKA
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    networks:
      - microservices-net
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 2181" ]
      interval: 30s
      timeout: 10s
      retries: 5

  kafka:
    image: 'bitnami/kafka:latest'
    user: root
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_LOG_CLEANER_ENABLE: 'true'
      KAFKA_JVM_PERFORMANCE_OPTS: -XX:MaxMetaspaceSize=128m -Xss512k
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - microservices-net
    deploy:
      resources:
        limits:
          memory: 3072MB
    oom_score_adj: -100
    healthcheck:
      test: [ "CMD-SHELL", "/opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list" ]
      interval: 30s
      timeout: 10s
      retries: 3

  # HAZELCAST
  hazelcast:
    image: hazelcast/hazelcast:5.5.0
    container_name: hazelcast
    ports:
      - "5701:5701"
    networks:
      - microservices-net

  # ZIPKIN
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - microservices-net
    restart: always

  # POSTGRES DATABASES
  postgres-auth:
    image: postgres:alpine
    container_name: postgres-auth
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth-service
    ports:
      - "5433:5433"
    command: -p 5433
    networks:
      - microservices-net
    restart: always

  postgres-user:
    image: postgres:alpine
    container_name: postgres-user
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user-management-service
    ports:
      - "5434:5434"
    command: -p 5434
    networks:
      - microservices-net
    restart: always

  postgres-patient:
    image: postgres:alpine
    container_name: postgres-patient
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: patient-service
    ports:
      - "5435:5435"
    command: -p 5435
    networks:
      - microservices-net
    restart: always

  postgres-report:
    image: postgres:alpine
    container_name: postgres-report
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: report-service
    ports:
      - "5436:5436"
    command: -p 5436
    networks:
      - microservices-net
    restart: always

  # MAIN SERVICES
  config-server:
    container_name: config-server
    image: omerasafbalikci/config-server:latest
    ports:
      - "8888:8888"
    volumes:
      - ./logs:/logs
    networks:
      - microservices-net
    depends_on:
      logstash:
        condition: service_healthy
      zipkin:
        condition: service_started
      prometheus:
        condition: service_started
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8888/actuator/health"]
      interval: 30s
      timeout: 60s
      retries: 5

  discovery-server:
    container_name: discovery-server
    image: omerasafbalikci/discovery-server:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8761:8761"
    volumes:
      - ./logs:/logs
    networks:
      - microservices-net
    depends_on:
      config-server:
        condition: service_healthy

  api-gateway:
    container_name: api-gateway
    image: omerasafbalikci/api-gateway:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs
    networks:
      - microservices-net
    depends_on:
      discovery-server:
        condition: service_started
      redis:
        condition: service_healthy

  auth-service:
    container_name: auth-service
    image: omerasafbalikci/auth-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./logs:/logs
    networks:
      - microservices-net
    depends_on:
      - api-gateway
      - rabbitmq
      - postgres-auth

  user-service:
    container_name: user-service
    image: omerasafbalikci/user-management-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./logs:/logs
    networks:
      - microservices-net
    depends_on:
      - api-gateway
      - auth-service
      - postgres-user

  patient-service:
    container_name: patient-service
    image: omerasafbalikci/patient-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6380
    volumes:
      - ./logs:/logs
    networks:
      - microservices-net
    depends_on:
      redis:
        condition: service_healthy
      api-gateway:
        condition: service_started
      postgres-patient:
        condition: service_started
      kafka:
        condition: service_healthy

  report-service:
    container_name: report-service
    image: omerasafbalikci/report-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./logs:/logs
    networks:
      - microservices-net
    depends_on:
      - api-gateway
      - postgres-report
      - patient-service

  analytics-service:
    container_name: analytics-service
    image: omerasafbalikci/analytics-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./logs:/logs
    networks:
      - microservices-net
    depends_on:
      - api-gateway
      - report-service
      - patient-service
      - hazelcast

networks:
  microservices-net:
    driver: bridge
    name: microservices-net