hazelcast:
  clusterName: fx‑rates
kafka:
  bootstrapServers: localhost:9092
  topic: ratehub.rates
threadPool:
  size: 32
subscribers:
  - class: com.ratedistribution.ratehub.subscriber.TcpSubscriber
    name: PF1
    host: 127.0.0.1
    port: 8800
    rates: [ "EURUSD", "USDTRY", "GBPUSD" ]
  - class: com.ratedistribution.ratehub.subscriber.RestSubscriber
    name: PF2
    host: http://localhost:8080
    port: 0
    rates: [ "EURUSD", "USDTRY", "GBPUSD" ]
calculations:
  - rateName: USDTRY
    engine: groovy
    bid: "(PF1_USDTRY_bid + PF2_USDTRY_bid) / 2"
    ask: "(PF1_USDTRY_ask + PF2_USDTRY_ask) / 2"
  - rateName: EURTRY
    engine: js
    bid: "((PF1_USDTRY_bid+PF2_USDTRY_bid)/2 + (PF1_USDTRY_ask+PF2_USDTRY_ask)/2)/2 * ((PF1_EURUSD_bid+PF2_EURUSD_bid)/2)"
    ask: "((PF1_USDTRY_bid+PF2_USDTRY_bid)/2 + (PF1_USDTRY_ask+PF2_USDTRY_ask)/2)/2 * ((PF1_EURUSD_ask+PF2_EURUSD_ask)/2)"
