# --- System settings --------------------------------------------------------
hazelcast:
  clusterName: fx‑rates
kafka:
  bootstrapServers: localhost:9092
  topic: fx‑rates
threadPool:
  size: 8

# --- Subscriber definitions (dynamic loading) ------------------------------
subscribers:
  - class: com.example.fxcoordinator.subscriber.impl.TcpSubscriber
    name: PF1
    host: 127.0.0.1
    port: 8081
    rates: [PF1_USDTRY, PF1_EURUSD, PF1_GBPUSD]
  - class: com.example.fxcoordinator.subscriber.impl.RestSubscriber
    name: PF2
    host: http://127.0.0.1:8080
    port: 0            # not used for REST but kept to satisfy constructor sig
    rates: [PF2_USDTRY, PF2_EURUSD, PF2_GBPUSD]

# --- Calculation formulas ---------------------------------------------------
calculations:
  - rateName: USDTRY
    engine: groovy
    bid: "(PF1_USDTRY.bid + PF2_USDTRY.bid)/2"
    ask: "(PF1_USDTRY.ask + PF2_USDTRY.ask)/2"
  - rateName: EURTRY
    engine: groovy
    helpers:
      usdMid: "((PF1_USDTRY.bid+PF2_USDTRY.bid)/2 + (PF1_USDTRY.ask+PF2_USDTRY.ask)/2)/2"
    bid: "usdMid * ((PF1_EURUSD.bid+PF2_EURUSD.bid)/2)"
    ask: "usdMid * ((PF1_EURUSD.ask+PF2_EURUSD.ask)/2)"
  - rateName: GBPTRY
    engine: groovy
    helpers:
      usdMid: "((PF1_USDTRY.bid+PF2_USDTRY.bid)/2 + (PF1_USDTRY.ask+PF2_USDTRY.ask)/2)/2"
    bid: "usdMid * ((PF1_GBPUSD.bid+PF2_GBPUSD.bid)/2)"
    ask: "usdMid * ((PF1_GBPUSD.ask+PF2_GBPUSD.ask)/2)"
  */