tcpServer:
  port: 8084

simulator:
  update-interval-millis: 1000
  max-updates: 0
  correlationMatrix:
    - [1.0, 0.20, 0.10]
    - [0.20, 1.0, 0.30]
    - [0.10, 0.30, 1.0]

  rates:
    - rateName: "PF1_EURUSD"
      initialPrice: 1.037
      drift: 0.0002
      baseSpread: 0.0002
      garchParams:
        omega:  0.0000001
        alpha: 0.05
        beta: 0.90
      jumpIntensity: 0.001
      jumpMean: 0.0
      jumpVol:  0.0005
      useMeanReversion: true
      kappa: 1.0
      theta: 1.037

    - rateName: "PF1_USDTRY"
      initialPrice: 18.0
      drift: 0.0005
      baseSpread: 0.02
      garchParams:
        omega:  0.000001
        alpha: 0.10
        beta: 0.85
      jumpIntensity: 0.001
      jumpMean: 0.002
      jumpVol: 0.02
      useMeanReversion: true
      kappa: 0.05
      theta: 18.5

    - rateName: "PF1_XAUUSD"
      initialPrice: 1850.0
      drift: 0.0001
      baseSpread: 0.5
      garchParams:
        omega:  0.000002
        alpha: 0.05
        beta: 0.90
      jumpIntensity: 0.0003
      jumpMean: 0.0
      jumpVol: 0.5
      useMeanReversion: false
      kappa: 0.0
      theta: 1800.0

  sessionVolFactors:
    - startHour: 0
      endHour: 6
      volMultiplier: 0.5
    - startHour: 6
      endHour: 13
      volMultiplier: 1.0
    - startHour: 13
      endHour: 17
      volMultiplier: 1.5
    - startHour: 17
      endHour: 24
      volMultiplier: 1.0

  holidays:
    - startDateTime: "2024-12-24T00:00:00Z"
      endDateTime:   "2024-12-26T00:00:00Z"
      name: "Christmas"
    - startDateTime: "2025-01-01T00:00:00Z"
      endDateTime:   "2025-01-02T00:00:00Z"
      name: "New Year"

  weekendHandling:
    enabled: true
    weekendGapJumpMean: 0.001
    weekendGapJumpVol: 0.005

  enableRegimeSwitching: true
  regimeLowVol:
    volScale: 1.0
    meanDuration: 200
    transitionProb: 0.05
  regimeHighVol:
    volScale: 3.0
    meanDuration: 50
    transitionProb: 0.10
