hazelcast:
  clusterName: fx-rates

kafka:
  bootstrapServers: kafka:9092
  rawTopic: ratehub.raw
  calcTopic: ratehub.calculated

threadPool:
  size: 32

auth:
  url: http://localhost:8080/auth/login
  username: omerasafbalikci
  password: omerasaf18993
  refreshSkewSeconds: 60

subscribers:
  - class: com.ratedistribution.ratehub.subscriber.impl.TcpSubscriber
    name: PF1
    host: 127.0.0.1
    port: 8084
    rates: [ "EURUSD", "USDTRY", "GBPUSD" ]

  - class: com.ratedistribution.ratehub.subscriber.impl.RestSubscriber
    name: PF2
    host: http://localhost:8080
    port: 0
    rates: [ "EURUSD", "USDTRY", "GBPUSD" ]

calculations:
  - rateName: EURUSD
    engine: groovy
    scriptPath: formulas/eurusd.groovy
    dependsOn: [ EURUSD, USDTRY ]

  - rateName: EURTRY
    engine: groovy
    scriptPath: formulas/eurtry.groovy

  - rateName: GBPTRY
    engine: js
    scriptPath: formulas/gbptry.js

  - rateName: USDTRY
    engine: java
    scriptPath: formulas/usdtry.java

mail:
  from: asafmarket.ltd@gmail.com
  password: ppqp daaa lgup oscr
  to: blkc.omerasaff@gmail.com
  smtpHost: smtp.gmail.com
  smtpPort: 587